### ISSUE TITLE
Lỗi add appota game sdk3 vào unity.

### ISSUE THREAD

**Issue by soibat** [appota/unity-game-sdk3#6]
Mình add file script C# trong start chứa hàm:
AppotaSDKHandler.Instance.Init();
AppotaSDKHandler.Instance.SetAutoShowLogin(false);

Gắn file vào Inpector để chạy chung khi game start, và trong logcat liên tục nhận lỗi như bên dưới. Khi nhấn button gọi các hàm ShowLoginView(), MakePayment() đều không được.

Unity 5.1.*
Android device 4.2.2

LogCat:

I/Unity   (  454):   at Appo
I/Unity   (  454): AndroidJavaException: java.lang.ClassNotFoundException: com.a
ppota.gamesdk.unity.UnityHandler
I/Unity   (  454):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] i
n <filename unknown>:0
I/Unity   (  454):   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPt
r clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unkn
own>:0
I/Unity   (  454):   at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObj
ect] (System.String methodName, System.Object[] args) [0x00000] in <filename unk
nown>:0
I/Unity   (  454):   at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObje
ct] (System.String methodName, System.Object[] args) [0x00000] in <filename unkn
own>:0
I/Unity   (  454):   at UnityEngine.AndroidJavaObject.FindClass (System.String n
ame) [0x00000] in <filename unknown>:0
I/Unity   (  454):   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.S
tring className) [0x00000] in <filename unknown>:0
I/Unity   (  454):   at UnityEngine.AndroidJavaClass..ctor (System.String classN
ame) [0x00000] in <filename unknown>:0
I/Unity   (  454):   at AppotaSDKHandler.IsUserLogin () [0x00000] in <filename u
nknown>:0

Mình phải xóa bỏ file jar:Plugins\Android\AppotaSDK\bin\appotagamesdkv3.jar do bị lỗi trong quá trình build do đụng thư viện. Trong game mình đang sử dụng các sdk:
- Google play game service
- Soomla
- Chartboost
Mình không nhận thấy appotagamesdkv3.jar đụng file jar nào nhưng khi bỏ nó thì mới có thể build. Không biết nó có anh hưởng đến lỗi bên trên không.

Nhờ mọi người hướng dẫn mình cách fix.
Thanks

**Comment by tutv2904** [comment]
Chào bạn.

Lỗi "AndroidJavaException: java.lang.ClassNotFoundException: com.a
ppota.gamesdk.unity.UnityHandler" là do ko thể tìm thấy class UnityHandler. Xoá thư viện appotagamesdkv3.jar là nguyên nhân của lỗi này. 

Bạn đã từng gắn AppotaGameSDK vào project bao giờ chưa? Nếu có thể thì liệt kê giúp mình danh sách các file jar bạn đang sử dụng trong project, và log build lỗi khi đang sử dụng file appotagamesdkv3.jar nhé.

**Comment by soibat** [comment]
Bạn cho mình hỏi appota game for unity sdk4 có triển khai sử dụng được chưa vậy?
Rất xin lỗi vì điều này nhưng do ko fix được lỗi nên mình đã chuyển sang dùng sdk4, Demo example chạy tốt tuy nhiên khi đưa vào project mình cũng bị đụng thư viện ko build được. Mình sẽ post issue lỗi bên đó trong vài ngày nữa, do bây giờ mình đang bận, mong bạn qua đó support giúp mình nhé.
Thanks.

**Comment by tutv2904** [comment]
Unity SDK4 đã triển khải sử dụng rồi nhé bạn. Tuy nhiên khi chuyển sang SDK4, bạn vẫn gặp issue trên là vì nguyên nhân sau: 
- Thư viện Soomla chứa file jar `AndroidStoreGooglePlay`, lib này cung cấp khả năng thanh toán Play Store cho ứng dụng. Tuy nhiên lib này trùng `interface com.android.vending.billing.IInAppBillingService` với thư viện `AppotaGameSDK`. Package này là bắt buộc đối với các thư viện thanh toán Play Store

Do vậy bạn nên xem xét về khả năng chỉ sử dụng 1 thư viện thanh toán trong project mà thôi. Nếu như bạn cần sử dụng Soomla ngoài mục đích thanh toán, thì bạn nên tìm hiểu về việc loại bỏ các thư viện thanh toán ra xem sao :)

**Comment by soibat** [comment]
Bạn cho mình hỏi, trong project mình có dùng Soomla Profile, Soomla core, soomla store.
Khi mình extract file jar bên appota ra thì mình nhận thấy trong Appota có twitter, facebook, IInAppBillingService.
Mà trong Soomla Profile cũng có facebook, twitter, Soomla Store có IInAppBillingService.
Trường hợp đụng thư viện như bạn nói bên trên (AndroidStoreGooglePlay) là đúng và mình có thể bỏ Soomala Store (chứa AndroidStoreGooglePlay) do bên Appota có hỗ trợ. Tuy nhiên mình nghĩ chắc facebook, twitter cũng có khả năng bị đụng. Nếu vậy việc loại bỏ toàn bộ soomla là rất khó cho bên mình, do mình cần Soomla Profile(hỗ trợ share facebook, twitter, gg plus).
Trong unity thường bị đụng thư viện, mình sẽ xóa chỉ chừa lại một thư viện duy nhất là build được.
Mình có thử extract appota_sdk4.jar ra rồi bỏ bớt thư viện và build lại nhưng ko thành công và bị lỗi không tìm thấy thư viện @@.
Nếu thật sự không còn cách nào khác thì đúng là phiền phức @@

**Comment by tutv2904** [comment]
Facebook, Twitter bên mình đã custom lại nên sẽ không bị conflict. Bạn sử dụng thoải mái Soomla Profile nhé ;)

**Comment by soibat** [comment]
Cảm ơn bạn đã support, mình sẽ thử loại bỏ Soomla Store thử.
